In [2]:
import numpy as np
import pandas as pd

In [3]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
a=np.empty([5,5],dtype=int)
a

array([[ 943806184,        533,         64,          0,          0],
       [         0,          0,          0,          0,    6881382],
       [1647600439, 1633772592, 1697919536,  842086198,  895891302],
       [ 892811568,  878928950,  845296441,  946025016,  942749751],
       [1630757432, 1717842789, 1667642469,  878863158, 1650800945]])

In [5]:
a=np.zeros([5,2])
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
a=np.zeros([6,8])
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
df=pd.DataFrame(a)
df
df.to_csv("asd.csv")

In [8]:
a=np.arange(3,98,6)
a

array([ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87, 93])

In [9]:
a=np.linspace(1,100,4)
a

array([  1.,  34.,  67., 100.])

In [10]:
a=np.linspace(1,499,5)
a

array([  1. , 125.5, 250. , 374.5, 499. ])

In [11]:
arr = np.array(42)
print(arr)
 
print(arr.ndim)

42
0


In [12]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(arr.ndim)

[1 2 3 4 5]
1


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [14]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [15]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

arr[1][1][1]

5

In [16]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print(arr.ndim)


[[[[[1 2 3 4]]]]]
5


In [17]:
a = np.random.rand()
a

0.7263443294583818

In [18]:
a = np.random.rand(50)
a

array([0.88528705, 0.36925586, 0.97647811, 0.04672241, 0.97782829,
       0.86991483, 0.71672005, 0.89862553, 0.76028   , 0.19189858,
       0.03331356, 0.47257071, 0.43738956, 0.26624405, 0.72903288,
       0.07543647, 0.93471064, 0.82285075, 0.57934821, 0.32530853,
       0.26679501, 0.09654049, 0.86673686, 0.21705575, 0.84231163,
       0.73431202, 0.50042992, 0.52451965, 0.58998002, 0.83676739,
       0.22536977, 0.27461921, 0.11780934, 0.68922912, 0.25226116,
       0.5775137 , 0.2606405 , 0.3332935 , 0.33808092, 0.96222784,
       0.66937815, 0.84169547, 0.7298563 , 0.73237907, 0.34889905,
       0.90534667, 0.30787601, 0.90172141, 0.51036729, 0.15180747])

In [19]:
a = np.random.rand(20)*100
a

array([43.76727611,  9.01557135, 51.21049762, 74.04280678, 10.26903037,
       31.90629007, 29.12107829, 68.68449477, 94.67305374, 17.0145082 ,
       27.25242705, 65.47801601, 10.35415015, 39.77550982, 51.29135755,
       66.20168527, 69.38897885, 53.77996815, 25.68933243, 61.4055586 ])

In [20]:
a = np.random.randint(20, size=(4))
a

array([ 3,  4, 12, 11])

In [21]:
a = np.random.randint(100, size=(5,4))
a

array([[95, 42, 72,  3],
       [41, 53, 68, 45],
       [16, 86, 10, 82],
       [62, 69, 74, 71],
       [28, 74, 20, 35]])

In [22]:
a = np.random.randint(10,200, size=(4,8))
a

array([[156, 116, 120, 140, 165, 123, 124,  35],
       [ 60,  60, 101, 157, 111,  61, 138,  41],
       [144, 144, 170, 148, 153,  15,  51, 108],
       [184, 177,  65,  34, 196,  44, 114,  60]])

In [23]:
a = np.random.choice([1,2,3,4,5])
a

2

In [24]:
a = np.random.choice([1,4,2,5,3, 5, 7, 9], size=(1, 2))
a

array([[7, 3]])

In [25]:
a = np.random.choice([1,4,2,5,3, 5, 7, 9], size=(2,3))

a

array([[4, 1, 7],
       [9, 4, 9]])

In [26]:
arr=np.array([1,2,3,4])
arr.dtype

dtype('int32')

In [27]:
arr = np.array(['python', 'java', 'c'])
arr.dtype

dtype('<U6')

In [28]:
arr = np.array([12.3,16.34,21.34])

new_arr = arr.astype(int)
new_arr

array([12, 16, 21])

In [29]:
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])
print(arr)
arr[1, 3]

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


90

In [30]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
arr[0, -2]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


4

In [31]:
lis1=[1,2,3,4,5]
lis2=[2,3,4,5,6]
lis3=[9,7,6,8,9]

arr=np.array([lis1,lis2,lis3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [32]:
arr[1:4,:-2]

array([[2, 3, 4],
       [9, 7, 6]])

In [33]:
arr[0:3:2,1:3]

array([[2, 3],
       [7, 6]])

In [34]:
arr[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [35]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr.shape

(2, 4)

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

print("     ")

new_arr = arr.reshape(4, 3)

print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
     
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

print("     ")

new_arr = arr.reshape(3,2,2)

print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
     
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

print("     ")

new_arr = arr.reshape(2,3,2)

print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
     
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [39]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

print("     ")

new_arr = arr.reshape(2, 6)

print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
     
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [41]:
lis1=[1,2,3,4,5]
lis2=[2,3,4,5,6]
lis3=[9,7,6,8,9]

arr=np.array([lis1,lis2,lis3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [42]:
np.nditer(arr)

In [43]:
for i in np.nditer(arr):
    print(i),

1
2
3
4
5
2
3
4
5
6
9
7
6
8
9


In [45]:

print(arr)

print("__________")

Tran_arry  = arr.T 

print(Tran_arry)


[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
__________
[[1 2 9]
 [2 3 7]
 [3 4 6]
 [4 5 8]
 [5 6 9]]


In [51]:
arr = np.array([7,2,23,15,11])
print(arr)

print('-'*40)
print(np.sort(arr))

[ 7  2 23 15 11]
----------------------------------------
[ 2  7 11 15 23]


In [55]:
arr = np.array([[20,10], [3,7]])
print(arr)
new_arr = np.sort(arr)        
new_arr

[[20 10]
 [ 3  7]]


array([[10, 20],
       [ 3,  7]])

In [56]:
arr = np.array([[20,10], [3,7]])
print(arr)
new_arr = np.sort(arr, axis = 0) 
new_arr

[[20 10]
 [ 3  7]]


array([[ 3,  7],
       [20, 10]])

In [57]:
arr = np.array([2,2,5,7,8,2,5,9])

x = np.where(arr == 2)

print(x)

(array([0, 1, 5], dtype=int32),)


In [53]:
arr = np.array([2,2,5,7,8,2,5,9])

x = np.where(arr >7,"hello",arr)

print(x)

['2' '2' '5' '7' 'hello' '2' '5' 'hello']


In [59]:
arr = np.array([2,2,5,7,8,2,5,9])

newarr = np.array_split(arr, 4)

print(newarr)

[array([2, 2]), array([5, 7]), array([8, 2]), array([5, 9])]


In [60]:
arr = np.array([2,2,5,7,8,2,5,9,72])

newarr = np.array_split(arr, 4)

print(newarr)

[array([2, 2, 5]), array([7, 8]), array([2, 5]), array([ 9, 72])]


In [61]:
arr = np.array([2,2,5,7,8,2,5,9,6,2])

newarr = np.array_split(arr, 4)

print(newarr)

[array([2, 2, 5]), array([7, 8, 2]), array([5, 9]), array([6, 2])]


In [63]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.concatenate((arr, arr1),axis=0)

arr

array([ 2,  4,  6,  8, 10, 12])

In [65]:
arr = np.array([[2, 4], [6, 8]])

arr1 = np.array([[10, 12], [14, 16]])

arr = np.concatenate((arr, arr1), axis=1) 

arr

array([[ 2,  4, 10, 12],
       [ 6,  8, 14, 16]])

In [66]:
arr = np.array([[2, 4], [6, 8]])

arr1 = np.array([[10, 12], [14, 16]])

arr = np.concatenate((arr, arr1), axis=0)

arr

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [67]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.hstack((arr, arr1))

arr

array([ 2,  4,  6,  8, 10, 12])

In [68]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.vstack((arr, arr1))

arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [69]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])


arr = np.dstack((arr, arr1))

arr

array([[[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

In [70]:
arr = np.array(["USA","INDIA","RUSSIA"])

new_arr = np.char.lower(arr)

new_arr

array(['usa', 'india', 'russia'], dtype='<U6')

In [71]:
arr= np.char.join('_', 'FINGERTIPS')
arr

array('F_I_N_G_E_R_T_I_P_S', dtype='<U19')

In [74]:
arr = np.array([2.344,6.232,8.34,5,3.5,4.36]) 

np.around(arr) 

array([2., 6., 8., 5., 4., 4.])

In [75]:
np.around(arr, decimals = 1) 

array([2.3, 6.2, 8.3, 5. , 3.5, 4.4])

In [76]:
np.floor(arr)

array([2., 6., 8., 5., 3., 4.])

In [77]:
np.ceil(arr)

array([3., 7., 9., 5., 4., 5.])

In [78]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])


In [79]:
np.add(arr,arr1)

array([10, 14, 18])

In [80]:
np.subtract(arr1,arr) 

array([6, 6, 6])

In [81]:
np.subtract(arr,arr1) 

array([-6, -6, -6])

In [82]:
np.abs(np.subtract(arr,arr1) )

array([6, 6, 6])

In [83]:
np.multiply(arr,arr1) 

array([16, 40, 72])

In [84]:
np.divide(arr1,arr)

array([4. , 2.5, 2. ])

In [85]:
np.power(arr,2) 

array([ 4, 16, 36], dtype=int32)

In [86]:
np.mod(arr1,arr) 

array([0, 2, 0], dtype=int32)

In [88]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [89]:
np.median(arr) 

6.5

In [90]:
np.mean(arr) 

6.5

In [91]:
np.average(arr)

6.5

In [92]:
np.std(arr)

3.452052529534663

In [93]:
np.var(arr)

11.916666666666666